spring:
  datasource:
    type:  com.alibaba.druid.pool.xa.DruidXADataSource
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      db1:
        name: db1
        url: jdbc:mysql://127.0.0.1/multi-db-1?useUnicode=true&characterEncoding=utf-8
        username: root
        password: 123456
        entity-packages: vip.xuejike.spring.boot.multidatasource.demo.db1
      db2:
        name: db2
        url: jdbc:mysql://127.0.0.1/multi-db-2?useUnicode=true&characterEncoding=utf-8
        username: root
        password: 123456
        entity-packages: vip.xuejike.spring.boot.multidatasource.demo.db2

  jpa:
    hibernate:
      ddl-auto: update
  jta:
    log-dir: classpath:tx-logs
    transaction-manager-id: txManager
#debug: true
